apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: aadityasharma96/multi-region-dashboard-backend
  newName: aadityasharma96/multi-region-dashboard-backend
  newTag: 22-623772c7
- name: aadityasharma96/multi-region-dashboard-frontend
  newName: aadityasharma96/multi-region-dashboard-frontend
  newTag: 22-623772c7
